### ISSUE TITLE
Given I have the app I am able to log in.

### ISSUE THREAD

**Issue by eddiejaoude** [DashboardHub/Jin-Mobile#5]
- Input box on top of beacon list page

OR
- First page simulate login by typing their name

**Comment by cnak** [comment]
For the time being this is completed faked with no db connections or validations happening.

**Comment by eddiejaoude** [comment]
![slack for ios upload](https://cloud.githubusercontent.com/assets/624760/19417161/87745e78-939d-11e6-8878-f3f869b20a5a.jpg)
